# Project information
site_name: Julia Torrejon
site_description: 'Personal Site'
site_author: 'Julia Torrejon'
site_url: 'https://juliatorrejon.com'

#Copyright
copyright: 'Copyright &copy; 2025 Julia Torrejon'

# Page tree
nav:
    - About: index.md
    - Portfolio: portfolio.md
    - Contact: contact.md
    #- Blog:
    #    - blog/index.md

# Configuration
theme:
    name: dracula
    palette:

      # # Palette toggle for light mode
      # - scheme: default
      #   primary: cyan
      #   accent: cyan
      #   toggle:
      #     icon: material/brightness-7
      #     name: Switch to dark mode

      # # Palette toggle for dark mode
      # - scheme: slate
      #   primary: cyan
      #   accent: cyan
      #   toggle:
      #     icon: material/brightness-4
      #     name: Switch to light mode

   # Language settings
    language: en


    # Navigation settings
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.path
      - toc.integrate
      - navigation.top
      - navigation.footer

plugins:
  - search:
      lang: en
  - tags
  # - blog:
  #     post_date_format: full

# Syntax highlighting
markdown_extensions:
  - codehilite
  - admonition

# Customization
extra:
    social:
      - icon: fontawesome/brands/github
        type: github-alt
        link: https://github.com/juliatorrejon
      - icon: fontawesome/brands/twitter
        type: twitter
        link: https://twitter.com/juliatorrejon
      - icon: fontawesome/brands/linkedin
        type: linkedin
        link: https://www.linkedin.com/in/juliatorrejon

    analytics:
      provider: google
      property: G-BQTFTTRB5X
