# Project information
site_name: Julia Torrejon
site_description: 'Personal Site'
site_author: 'Julia Torrejon'
site_url: 'https://juliatorrejon.com'

#Copyright
copyright: 'Copyright &copy; 2023 Julia Torrejon'

# Page tree
nav:
    - Overview: index.md
    - About: about.md
    - Documentation:
      - Algorithms:
        - Overview: documentation/algorithms-overview.md
        - Big O Notation: documentation/big-o-notation.md
      - Cloud: 
        - GCP Services Overview: documentation/gcp-services-overview.md
        - AWS Services Overview: documentation/aws-services-overview.md
      - Computer Science: documentation/computer-science.md
      - Containers:
        - Docker Cheatsheet: documentation/docker-cheatsheet.md
        - Kubernetes Cheatsheet: documentation/kubernetes-cheatsheet.md
      - Data Structures:
        - Overview: documentation/data-structures-overview.md
        - Stacks: documentation/stacks.md
        - Queues: documentation/queues.md
        - Deques: documentation/deques.md
        - Linked Lists: documentation/linked-lists.md
        - Recursion: documentation/recursion.md
        - Searching: documentation/searching.md
        - Hash Tables: documentation/hash-tables.md
        - Trees: documentation/trees.md
        - Graphs: documentation/graphs.md
      - DevOps:
        - DevOps Roadmap: documentation/devops-roadmap.md
        - Cloud Formation Basics: documentation/cloud-formation-basics.md
      - Microservices: documentation/microservices.md
      - Object Oriented Programming: documentation/object-oriented-programming.md
      - Python: 
        - Python 2: documentation/python-2.md
      - Software Development:
        - Development Tools: documentation/development-tools.md
      - Software Testing: documentation/software-testing.md
    - Portfolio: portfolio.md
    - Contact: contact.md


# Configuration
theme:
    name: 'material'
    palette:

      # Palette toggle for light mode
      - scheme: default
        primary: cyan
        accent: cyan
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        primary: cyan
        accent: cyan
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

   # Language settings
    language: en


    # Navigation settings
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.path
      - toc.integrate
      - navigation.top
      - navigation.footer

plugins:
  - search:
      lang: en
  - tags

# Syntax highlighting
markdown_extensions:
  - codehilite
  - admonition

# Customization
extra:
    social:
      - icon: fontawesome/brands/github
        type: github-alt
        link: https://github.com/juliatorrejon
      - icon: fontawesome/brands/twitter
        type: twitter
        link: https://twitter.com/juliatorrejon
      - icon: fontawesome/brands/linkedin
        type: linkedin
        link: https://www.linkedin.com/in/juliatorrejon

    analytics:
      provider: google
      property: G-BQTFTTRB5X
